kind: pipeline
name: ts-base-node-ci

steps:
  - name: npm
    image: plugins/npm
    settings:
      email:
        from_secret: npm_email
      username:
        from_secret: npm_username
      password:
        from_secret: npm_password
      token:
        from_secret: npm_token
    when:
      event: push
      branch: master
