#!/bin/sh

# Installing dependencies
npm i

# Removing extra files
rm -rf .git
rm -rf init.sh

echo "Happy coding!\n"

echo "\tnpm run start-ts    run TS"
echo "\tnpm run lint        lint"
echo "\tnpm run test        run tests"
echo "\tnpm run build       build JS"
echo "\tnpm start           run builded JS\n"